#
# Modify the variables to set your keys
#
<<<<<<< HEAD
<<<<<<< HEAD
MAPS_API_KEY=AIzaSyDhNWpn9mdeWZsutL7Oe_X1m9n-KSgN7JQ
OPENPOSITIONING_API_KEY=KgmBKcA_WSnBmPVJCpOBtg
OPENPOSITIONING_MASTER_KEY=ewireless
=======

=======
>>>>>>> 316d004 (New Feature, UI refurbished (#20))
MAPS_API_KEY=AIzaSyAGqo26Wz1SUnGYP3TDDxLSDNK-EvHHtNc
OPENPOSITIONING_API_KEY=ClVYqwVfheyMZAUbyDvpVQ
OPENPOSITIONING_MASTER_KEY=ewireless
>>>>>>> 5ecdd7a (repeat 3 times secrets.properties)
